<a href="https://colab.research.google.com/github/ashm212/Bayesian-Learning/blob/main/Bayesian_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd 
df = pd.read_csv(r'/content/iris.csv')

In [4]:
df_train = df.sample(frac=0.8, random_state=1)
df_test=df.drop(df_train.index)
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [5]:
df_train['quantile_SL_Disc'] = pd.qcut(df['sepal.length'], q=4,labels=None)
df_train['quantile_SW_Disc'] = pd.qcut(df['sepal.width'], q=4,labels=None)
df_train['quantile_PL_Disc'] = pd.qcut(df['petal.length'], q=4,labels=None)
df_train['quantile_PW_Disc'] = pd.qcut(df['petal.width'], q=4,labels=None)

In [6]:
df_train.head()

,sepal.length,sepal.width,petal.length,petal.width,variety,quantile_SL_Disc,quantile_SW_Disc,quantile_PL_Disc,quantile_PW_Disc
14,5.8,4.0,1.2,0.2,Setosa,"(5.1, 5.8]","(3.3, 4.4]","(0.999, 1.6]","(0.099, 0.3]"
98,5.1,2.5,3.0,1.1,Versicolor,"(4.2989999999999995, 5.1]","(1.999, 2.8]","(1.6, 4.35]","(0.3, 1.3]"
75,6.6,3.0,4.4,1.4,Versicolor,"(6.4, 7.9]","(2.8, 3.0]","(4.35, 5.1]","(1.3, 1.8]"
16,5.4,3.9,1.3,0.4,Setosa,"(5.1, 5.8]","(3.3, 4.4]","(0.999, 1.6]","(0.3, 1.3]"
131,7.9,3.8,6.4,2.0,Virginica,"(6.4, 7.9]","(3.3, 4.4]","(5.1, 6.9]","(1.8, 2.5]"

In [8]:
df_train[['SL_low','SL_high']] = df_train['quantile_SL_Disc'].astype(str).str.split(',',expand=True)
df_train[['SW_low','SW_high']] = df_train['quantile_SW_Disc'].astype(str).str.split(',',expand=True)
df_train[['PL_low','PL_high']] = df_train['quantile_PL_Disc'].astype(str).str.split(',',expand=True)
df_train[['PW_low','PW_high']] = df_train['quantile_PW_Disc'].astype(str).str.split(',',expand=True)

In [9]:
df_train.head()

,sepal.length,sepal.width,petal.length,petal.width,variety,quantile_SL_Disc,quantile_SW_Disc,quantile_PL_Disc,quantile_PW_Disc,SL_low,SL_high,SW_low,SW_high,PL_low,PL_high,PW_low,PW_high
14,5.8,4.0,1.2,0.2,Setosa,"(5.1, 5.8]","(3.3, 4.4]","(0.999, 1.6]","(0.099, 0.3]",(5.1,5.8],(3.3,4.4],(0.999,1.6],(0.099,0.3]
98,5.1,2.5,3.0,1.1,Versicolor,"(4.2989999999999995, 5.1]","(1.999, 2.8]","(1.6, 4.35]","(0.3, 1.3]",(4.2989999999999995,5.1],(1.999,2.8],(1.6,4.35],(0.3,1.3]
75,6.6,3.0,4.4,1.4,Versicolor,"(6.4, 7.9]","(2.8, 3.0]","(4.35, 5.1]","(1.3, 1.8]",(6.4,7.9],(2.8,3.0],(4.35,5.1],(1.3,1.8]
16,5.4,3.9,1.3,0.4,Setosa,"(5.1, 5.8]","(3.3, 4.4]","(0.999, 1.6]","(0.3, 1.3]",(5.1,5.8],(3.3,4.4],(0.999,1.6],(0.3,1.3]
131,7.9,3.8,6.4,2.0,Virginica,"(6.4, 7.9]","(3.3, 4.4]","(5.1, 6.9]","(1.8, 2.5]",(6.4,7.9],(3.3,4.4],(5.1,6.9],(1.8,2.5]

In [11]:
df_train['SL_low']=df_train['SL_low'].str.replace('(','')
df_train['SL_high']=df_train['SL_high'].str.replace(']','')
df_train['SW_low']=df_train['SW_low'].str.replace('(','')
df_train['SW_high']=df_train['SW_high'].str.replace(']','')
df_train['PL_low']=df_train['PL_low'].str.replace('(','')
df_train['PL_high']=df_train['PL_high'].str.replace(']','')
df_train['PW_low']=df_train['PW_low'].str.replace('(','')
df_train['PW_high']=df_train['PW_high'].str.replace(']','')
df_train.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

,sepal.length,sepal.width,petal.length,petal.width,variety,quantile_SL_Disc,quantile_SW_Disc,quantile_PL_Disc,quantile_PW_Disc,SL_low,SL_high,SW_low,SW_high,PL_low,PL_high,PW_low,PW_high
14,5.8,4.0,1.2,0.2,Setosa,"(5.1, 5.8]","(3.3, 4.4]","(0.999, 1.6]","(0.099, 0.3]",5.1,5.8,3.3,4.4,0.999,1.6,0.099,0.3
98,5.1,2.5,3.0,1.1,Versicolor,"(4.2989999999999995, 5.1]","(1.999, 2.8]","(1.6, 4.35]","(0.3, 1.3]",4.2989999999999995,5.1,1.999,2.8,1.6,4.35,0.3,1.3
75,6.6,3.0,4.4,1.4,Versicolor,"(6.4, 7.9]","(2.8, 3.0]","(4.35, 5.1]","(1.3, 1.8]",6.4,7.9,2.8,3.0,4.35,5.1,1.3,1.8
16,5.4,3.9,1.3,0.4,Setosa,"(5.1, 5.8]","(3.3, 4.4]","(0.999, 1.6]","(0.3, 1.3]",5.1,5.8,3.3,4.4,0.999,1.6,0.3,1.3
131,7.9,3.8,6.4,2.0,Virginica,"(6.4, 7.9]","(3.3, 4.4]","(5.1, 6.9]","(1.8, 2.5]",6.4,7.9,3.3,4.4,5.1,6.9,1.8,2.5

In [ ]:
#group by low high and count for each flower
#setosa probability
df_setosa = df_train[df_train['variety'].isin(['Setosa'])]
df_setosa = df_setosa.groupby(['quantile_SL_Disc']).size().reset_index(name='count')

#probability of setosa given that it has that sepal length quantile group i.e p(that quantile group | setosa)
df_setosa['probability_setosa_sepal_length'] = df_setosa['count']/df_setosa['count'].sum()

df_setosa.head()

            quantile_SL_Disc  count  probability_setosa_sepal_length
0  (4.2989999999999995, 5.1]     27                            0.675
1                 (5.1, 5.8]     13                            0.325
2                 (5.8, 6.4]      0                            0.000
3                 (6.4, 7.9]      0                            0.000

In [ ]:
#group by low high and count for each flower
#virginica probability
df_virginica = df_train[df_train['variety'].isin(['Virginica'])]
df_virginica = df_virginica.groupby(['quantile_SL_Disc']).size().reset_index(name='count')

#probability of virginica given that it has that sepal length quantile group i.e p(that quantile group | setosa)
df_virginica['probability_virginica_sepal_length'] = df_virginica['count']/df_virginica['count'].sum()

df_virginica.head()

            quantile_SL_Disc  count  probability_virginica_sepal_length
0  (4.2989999999999995, 5.1]      1                            0.023256
1                 (5.1, 5.8]      4                            0.093023
2                 (5.8, 6.4]     14                            0.325581
3                 (6.4, 7.9]     24                            0.558140

In [ ]:
#group by low high and count for each flower
#Versicolor probability
df_Versicolor = df_train[df_train['variety'].isin(['Versicolor'])]
df_Versicolor = df_Versicolor.groupby(['quantile_SL_Disc']).size().reset_index(name='count')

#probability of virginica given that it has that sepal length quantile group i.e p(that quantile group | setosa)
df_Versicolor['probability_Versicolor_sepal_length'] = df_Versicolor['count']/df_Versicolor['count'].sum()

df_Versicolor.head()

            quantile_SL_Disc  count  probability_Versicolor_sepal_length
0  (4.2989999999999995, 5.1]      2                             0.054054
1                 (5.1, 5.8]     16                             0.432432
2                 (5.8, 6.4]     12                             0.324324
3                 (6.4, 7.9]      7                             0.189189